---
title: "BIOSTAT707_EDA_Peijin_Wang"
author: "Peijin Wang"
date: "9/27/2021"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	message = FALSE,
	warning = FALSE
)
```

## Explortary Data Analysis

```{r}
library(tidyverse)
library(patchwork)
library(here)

library(corrplot)

```

EDA for financial variables, including exchange rate, unemployment, interest rate and unemployment rate.

#### Time series plot

##### 1. Exchange rate (daily)
```{r}

covid_full = read.csv(here("Rmarkdown/covid_full.csv"))
covid_full$date = as.Date(as.character(covid_full$date), format = "%Y-%m-%d")
```



```{r}
covid_full$Interest_Rate = as.numeric(covid_full$Interest_Rate)
covid_full$GDP = as.numeric(covid_full$GDP)


finance = covid_full %>% 
  select(date, id, administrative_area_level_1,
         exchange, GDP, Interest_Rate, unemployment)

```

```{r}
summary(finance)

sd(finance$exchange,na.rm = T)
sd(finance$GDP,na.rm = T)
sd(finance$Interest_Rate,na.rm = T)
sd(finance$unemployment,na.rm = T)

sum(is.na(finance$exchange))/nrow(covid_full)*100
sum(is.na(finance$GDP))/nrow(covid_full)*100
sum(is.na(finance$Interest_Rate))/nrow(covid_full)*100
sum(is.na(finance$unemployment))/nrow(covid_full)*100
```



```{r fig.height=5, fig.width=10}
exchange_sort_id = finance %>% 
  select(date, id, administrative_area_level_1, exchange) %>% 
  na.omit() %>% 
  group_by(id) %>% 
  mutate(mean = mean(exchange)) %>% 
  arrange(mean, id, date) %>% 
  select(-mean) %>% select(id) %>% unique()

exchange_low =finance %>% 
  select(date, id, administrative_area_level_1, exchange) %>% 
  na.omit() %>% 
  filter(id == unlist(head(exchange_sort_id,n = 5)))

exchange_high = finance %>% 
  select(date, id, administrative_area_level_1, exchange) %>% 
  na.omit() %>% 
  filter(id == unlist(tail(exchange_sort_id,n = 5)))


plot_exchange_low = ggplot(data = exchange_low,
                           aes(x = date,y = exchange,
                               color = administrative_area_level_1)) +
  geom_line() +
  scale_color_brewer(palette = "Set1", name = "Country") +
  labs(x = "Time",
       y = "Exchange rate to SDR (daily)",
       title = "a) Top five countries with the smallest average exchange rate",
       subtitle = "SDR = Special Drawing Rights")

plot_exchange_high = ggplot(data = exchange_high,
                           aes(x = date,y = exchange,
                               color = administrative_area_level_1)) +
  geom_line() +
  scale_color_brewer(palette = "Set2", name = "Country") +
  labs(x = "Time",
       y = "Exchange rate to SDR (daily)",
       title = "b) Top five countries with the largest average exchange rate",
       subtitle = "SDR = Special Drawing Rights")




```


##### 2. unemployment (monthly)
```{r fig.height=5, fig.width=12}
# Order of unemployment rate by country from low to high
unemployment_sort_id = finance %>% 
  select(date, id, administrative_area_level_1, unemployment) %>% 
  na.omit() %>% 
  group_by(id) %>% 
  mutate(mean = mean(unemployment)) %>% 
  arrange(mean, id, date) %>% 
  select(-mean) %>% select(id) %>% unique()

unemployment_low = finance %>% 
  select(date, id, administrative_area_level_1, unemployment) %>% 
  na.omit() %>% 
  filter(id == unlist(head(unemployment_sort_id,n = 5)))

unemployment_high = finance %>% 
  select(date, id, administrative_area_level_1, unemployment) %>% 
  na.omit() %>% 
  filter(id == unlist(tail(unemployment_sort_id,n = 5)))


plot_unemployment_low = ggplot(data = unemployment_low,
                           aes(x = date,y = unemployment,
                               color = administrative_area_level_1)) +
  geom_line() +
  scale_color_brewer(palette = "Spectral", name = "Country",direction = 1) +
  labs(x = "Time",
       y = "Unemployment rate (monthly)",
       title = "c) Top five countries with the smallest average unemployment rate")

plot_unemployment_high = ggplot(data = unemployment_high,
                           aes(x = date,y = unemployment,
                               color = administrative_area_level_1)) +
  geom_line() +
  scale_color_brewer(palette = "Spectral", name = "Country", direction = -1) +
  labs(x = "Time",
       y = "Unemployment rate (monthly)",
       title = "d) Top five countries with the largest average unemployment rate")

plot_exchange_low + plot_exchange_high + plot_unemployment_low + plot_unemployment_high

```


#### Correlation plots
```{r fig.height=7, fig.width=7}
covid_finance_nona = covid_full %>% 
  select(vaccines, tests, confirmed, recovered, deaths, stringency_index,
         exchange, GDP, Interest_Rate, unemployment,
         population, tmp) %>% na.omit()

corr = cor(covid_finance_nona)
corr_test = cor.mtest(covid_finance_nona, conf.level = 0.95)
corr_col = hcl.colors(10, "YlOrRd", rev = TRUE)

corrplot(corr, p.mat = corr_test$p, method = "circle", insig = "blank",
         addCoef.col = 'black',col = corr_col,
         number.digits = 2,
         number.cex = 1,
         tl.col="navy", 
         tl.srt=45,#Text label color and rotation
         diag = F, # hide correlation coefficient on the principal diagonal
         type="lower",
         mar=c(0,0,1,0))

mtext("Correlation plot for covid variables and potential continuous predictors", 
      at=6, line= 1.3, cex=1.2)

```

