---
title: "Classification"
author: "Pu Zeng"
date: "11/9/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tree)
library(randomForest)
library(tidyverse)
library(magrittr)
library(reshape)
library(patchwork)
library(ggplot2)
library(gmodels)
library(rpart)
library(e1071)
library(caret)
library(flextable)
library(ROCR)
```

```{r}
weekly_covid_url_1 = "https://raw.githubusercontent.com/puzeng/BIOSTAT707_Course_Project/main/COVID_Complete/covid_1.csv"
covid_weekly_1 = read_csv(weekly_covid_url_1)


weekly_covid_url_2 = "https://raw.githubusercontent.com/puzeng/BIOSTAT707_Course_Project/main/COVID_Complete/covid_2.csv"
covid_weekly_2 = read_csv(weekly_covid_url_2)

weekly_covid_url_3 = "https://raw.githubusercontent.com/puzeng/BIOSTAT707_Course_Project/main/COVID_Complete/covid_3.csv"
covid_weekly_3 = read_csv(weekly_covid_url_3)

weekly_covid_url_4 = "https://raw.githubusercontent.com/puzeng/BIOSTAT707_Course_Project/main/COVID_Complete/covid_4.csv"
covid_weekly_4 = read_csv(weekly_covid_url_4)

weekly_covid_url_5 = "https://raw.githubusercontent.com/puzeng/BIOSTAT707_Course_Project/main/COVID_Complete/covid_5.csv"
covid_weekly_5 = read_csv(weekly_covid_url_5)

```

```{r}

covid_weekly_1 = covid_weekly_1[, -c(4,5,6,7)]
covid_weekly_2 = covid_weekly_2[, -c(4,5,6,7)]
covid_weekly_3 = covid_weekly_3[, -c(4,5,6,7)]
covid_weekly_4 = covid_weekly_4[, -c(4,5,6,7)]
covid_weekly_5 = covid_weekly_5[, -c(4,5,6,7)]


covid_weekly_1$cluster = if_else(covid_weekly_1$newcases_p > median(covid_weekly_1$newcases_p, na.rm = TRUE), 1, 0)
covid_weekly_2$cluster = if_else(covid_weekly_1$newcases_p > median(covid_weekly_2$newcases_p, na.rm = TRUE), 1, 0)
covid_weekly_3$cluster = if_else(covid_weekly_1$newcases_p > median(covid_weekly_3$newcases_p, na.rm = TRUE), 1, 0)
covid_weekly_4$cluster = if_else(covid_weekly_1$newcases_p > median(covid_weekly_4$newcases_p, na.rm = TRUE), 1, 0)
covid_weekly_5$cluster = if_else(covid_weekly_1$newcases_p > median(covid_weekly_5$newcases_p, na.rm = TRUE), 1, 0)

covid_weekly_1$cluster = as.factor(covid_weekly_1$cluster)
covid_weekly_2$cluster = as.factor(covid_weekly_2$cluster)
covid_weekly_3$cluster = as.factor(covid_weekly_3$cluster)
covid_weekly_4$cluster = as.factor(covid_weekly_4$cluster)
covid_weekly_5$cluster = as.factor(covid_weekly_5$cluster)

covid_weekly_1 = covid_weekly_1[,-which(colnames(covid_weekly_1) %in%  c("newcases_p", "vaccines_count", "newcases"))]
covid_weekly_2 = covid_weekly_2[,-which(colnames(covid_weekly_2) %in% c("newcases_p", "vaccines_count", "newcases"))]
covid_weekly_3 = covid_weekly_3[,-which(colnames(covid_weekly_3) %in% c("newcases_p", "vaccines_count", "newcases"))]
covid_weekly_4 = covid_weekly_4[,-which(colnames(covid_weekly_4) %in% c("newcases_p", "vaccines_count", "newcases"))]
covid_weekly_5 = covid_weekly_5[,-which(colnames(covid_weekly_5) %in% c("newcases_p", "vaccines_count", "newcases"))]
```



```{r message=FALSE, warning=FALSE}
library(pROC)
set.seed(2021)

val_sets = createFolds(covid_weekly_1$cluster, k = 5)

error_rate_1 = NULL
acc_rate_1 = NULL
F1_1 = NULL
AUC_1 = NULL

for(i in 1:5){
  test_df = covid_weekly_1[val_sets[[i]], 4:ncol(covid_weekly_1)]
  train_df = covid_weekly_1[-val_sets[[i]], 4:ncol(covid_weekly_1)]
  set.seed(2021)
  decision_tree = rpart(cluster ~ ., data = train_df, control = rpart.control(minsplit = 19 ,cp = 0.0041667))

  prediction = predict(decision_tree, test_df, type = "class")


  precision_val = posPredValue(prediction, test_df$cluster, positive = "1")
  recall_val = sensitivity(prediction, test_df$cluster, positive = "1")

  acc_rate_1[i] = sum(prediction == test_df$cluster)/length(prediction)
  error_rate_1[i] = sum(prediction != test_df$cluster)/length(prediction)
  F1_1[i] = (2* precision_val * recall_val) / (precision_val + recall_val)
  AUC_1[i] = auc(test_df$cluster, as.numeric(prediction))
}

printcp(decision_tree)


DT_metrics_1 = data.frame(Accuracy = acc_rate_1, 
                          Error_Rate = error_rate_1, 
                          F1 = F1_1, 
                          AUC_ROC = AUC_1,
                          Fold_num  = 1:5, 
                          Set_NO = 1)

#val_sets = createFolds(covid_weekly_2$cluster, k = 5)

error_rate_2 = NULL
acc_rate_2 = NULL
F1_2 = NULL
AUC_2 = NULL

for(i in 1:5){
  test_df = covid_weekly_2[val_sets[[i]], 4:ncol(covid_weekly_2)]
  train_df = covid_weekly_2[-val_sets[[i]],4:ncol(covid_weekly_2)]
  set.seed(2021)
  decision_tree = rpart(cluster ~ ., data = train_df, control = rpart.control(minsplit = 16,cp = 0.0042735))
  
  prediction = predict(decision_tree, test_df, type = "class")
  precision_val = posPredValue(prediction, test_df$cluster, positive = "1")
  recall_val = sensitivity(prediction, test_df$cluster, positive = "1")
  
  acc_rate_2[i] = sum(prediction == test_df$cluster)/length(prediction)
  error_rate_2[i] = sum(prediction != test_df$cluster)/length(prediction)
  F1_2[i] = (2* precision_val * recall_val) / (precision_val + recall_val)
  AUC_2[i] = auc(test_df$cluster, as.numeric(prediction))
}
printcp(decision_tree)

DT_metrics_2 = data.frame(Accuracy = acc_rate_2, 
                          Error_Rate = error_rate_2, 
                          F1 = F1_2, 
                          AUC_ROC = AUC_2,
                          Fold_num  = 1:5, 
                          Set_NO = 2)
#val_sets = createFolds(covid_weekly_3$cluster, k = 5)

error_rate_3 = NULL
acc_rate_3 = NULL
F1_3 = NULL
AUC_3 = NULL

for(i in 1:5){
  test_df = covid_weekly_3[val_sets[[i]], 4:ncol(covid_weekly_3)]
  train_df = covid_weekly_3[-val_sets[[i]], 4:ncol(covid_weekly_3)]
  set.seed(2021)
  decision_tree = rpart(cluster ~ ., data = train_df, control = rpart.control(minsplit = 14, cp = 0.0056818))
  
  prediction = predict(decision_tree, test_df, type = "class")
  precision_val = posPredValue(prediction, test_df$cluster, positive = "1")
  recall_val = sensitivity(prediction, test_df$cluster, positive = "1")
  
  acc_rate_3[i] = sum(prediction == test_df$cluster)/length(prediction)
  error_rate_3[i] = sum(prediction != test_df$cluster)/length(prediction)
  F1_3[i] = (2* precision_val * recall_val) / (precision_val + recall_val)
  AUC_3[i] = auc(test_df$cluster, as.numeric(prediction))
}
printcp(decision_tree)

DT_metrics_3 = data.frame(Accuracy = acc_rate_3, 
                          Error_Rate = error_rate_3, 
                          F1 = F1_3, 
                          AUC_ROC = AUC_3,
                          Fold_num  = 1:5, 
                          Set_NO = 3)

#val_sets = createFolds(covid_weekly_4$cluster, k = 5)

error_rate_4 = NULL
acc_rate_4 = NULL
F1_4 = NULL
AUC_4 = NULL

for(i in 1:5){
  test_df = covid_weekly_4[val_sets[[i]], 4:ncol(covid_weekly_4)]
  train_df = covid_weekly_4[-val_sets[[i]],4:ncol(covid_weekly_4)]
  decision_tree = rpart(cluster ~ ., data = train_df, control = rpart.control(minsplit = 17, cp = 0.0028329))
  
  prediction = predict(decision_tree, test_df, type = "class")
  precision_val = posPredValue(prediction, test_df$cluster, positive = "1")
  recall_val = sensitivity(prediction, test_df$cluster, positive = "1")
  
  acc_rate_4[i] = sum(prediction == test_df$cluster)/length(prediction)
  error_rate_4[i] = sum(prediction != test_df$cluster)/length(prediction)
  F1_4[i] = (2* precision_val * recall_val) / (precision_val + recall_val)
  AUC_4[i] = auc(test_df$cluster, as.numeric(prediction))
}

printcp(decision_tree)

DT_metrics_4 = data.frame(Accuracy = acc_rate_4, 
                          Error_Rate = error_rate_4, 
                          F1 = F1_4, 
                          AUC_ROC = AUC_4,
                          Fold_num  = 1:5, 
                          Set_NO = 4)


#val_sets = createFolds(covid_weekly_5$cluster, k = 5)

error_rate_5 = NULL
acc_rate_5 = NULL
F1_5 = NULL
AUC_5 = NULL

for(i in 1:5){
  test_df = covid_weekly_5[val_sets[[i]], 4:ncol(covid_weekly_5)]
  train_df = covid_weekly_5[-val_sets[[i]], 4:ncol(covid_weekly_5)]
  decision_tree = rpart(cluster ~ ., data = train_df, control = rpart.control(minsplit = 18, cp = 0.001))
  
  prediction = predict(decision_tree, test_df, type = "class")
  precision_val = posPredValue(prediction, test_df$cluster, positive = "1")
  recall_val = sensitivity(prediction, test_df$cluster, positive = "1")
  
  acc_rate_5[i] = sum(prediction == test_df$cluster)/length(prediction)
  error_rate_5[i] = sum(prediction != test_df$cluster)/length(prediction)
  F1_5[i] = (2* precision_val * recall_val) / (precision_val + recall_val)
  AUC_5[i] = auc(test_df$cluster, as.numeric(prediction))
}
printcp(decision_tree)


DT_metrics_5 = data.frame(Accuracy = acc_rate_5, 
                          Error_Rate = error_rate_5, 
                          F1 = F1_5, 
                          AUC_ROC = AUC_5,
                          Fold_num  = 1:5, 
                          Set_NO = 5)

DT_metrics = rbind.data.frame(DT_metrics_1, DT_metrics_2, DT_metrics_3, DT_metrics_4, DT_metrics_5)

AVE_DT_metrics = DT_metrics %>% group_by(Set_NO) %>% summarise(Ave_Accuracy = mean(Accuracy),
                                                               Ave_Error_Rate = mean(Error_Rate),
                                                               Ave_F1_score = mean(F1),
                                                               AVE_AUC_ROC = mean(AUC_ROC))
AVE_DT_metrics
#AVE_DT_metrics$`Ave_Accuracy` = round(AVE_DT_metrics$`Ave_Accuracy`, 4)
#AVE_DT_metrics$`Ave_Error_Rate` = round(AVE_DT_metrics$`Ave_Error_Rate`, 4)

colnames(AVE_DT_metrics) = c("covid # data set", "5-folds CV Average Accuracy Rate", "5-folds CV Average Error Rate", "5-folds CV Average F1", "5-folds CV Average AUC-ROC")
AVE_DT_metrics[, 2:ncol(AVE_DT_metrics)] = round(AVE_DT_metrics[, 2:ncol(AVE_DT_metrics)], 4)

flextable(AVE_DT_metrics)
```
```{r}
plotcp(decision_tree)
```


```{r}

rpart.plot(decision_tree, 
           fallen.leaves = TRUE,
           faclen = 3, 
           clip.right.labs = T,
           type = 0, extra = 0, branch = FALSE, cex = 0.85,
    box.col=c("gray", "orange")[decision_tree$frame$yval])

#text(decision_tree, cex = 0.5)

```



```{r eval=FALSE, include=FALSE}
control = trainControl(method = "repeatedcv", number = 10, repeats = 3)
tunegrid = expand.grid(.mtry = c(1:10), .ntree = c(60, 80, 100, 120))

customRF = list(type = "Classification", library = "randomForest", loop = NULL)
customRF$parameters = data.frame(parameter = c("mtry", "ntree"),
                                 class = rep("numeric", 2),
                                 label =  c("mtry", "ntree"))

customRF$grid <- function(x, y, len = NULL, search = "grid") {}

customRF$fit <- function(x, y, wts, param, lev, last, weights, classProbs, ...) {
  randomForest(x, y, mtry = param$mtry, ntree=param$ntree, ...)
}

customRF$predict <- function(modelFit, newdata, preProc = NULL, submodels = NULL)
   predict(modelFit, newdata)

customRF$prob <- function(modelFit, newdata, preProc = NULL, submodels = NULL)
   predict(modelFit, newdata, type = "prob")

customRF$sort <- function(x) x[order(x[,1]),]

customRF$levels <- function(x) x$classes

set.seed(2021)

custom = train(cluster~.,
               data = covid_weekly_1[, 4:ncol(covid_weekly_1)],
               method = customRF,
               tuneGrid=tunegrid,
               trControl=control)
```

```{r}
plot(custom)
```

```{r eval=FALSE, include=FALSE}
set.seed(2021)

custom = train(cluster~.,
               data = covid_weekly_2[, 4:ncol(covid_weekly_2)],
               method = customRF,
               tuneGrid=tunegrid,
               trControl=control)

```

```{r eval=FALSE, include=FALSE}
plot(custom)
```


```{r eval=FALSE, include=FALSE}
set.seed(2021)
custom = train(cluster~.,
               data = covid_weekly_3[, 4:ncol(covid_weekly_3)],
               method = customRF,
               tuneGrid=tunegrid,
               trControl=control)

plot(custom)
```

```{r eval=FALSE, include=FALSE}
set.seed(2021)
custom = train(cluster~.,
               data = covid_weekly_4[, 4:ncol(covid_weekly_4)],
               method = customRF,
               tuneGrid=tunegrid,
               trControl=control)


plot(custom)
```

```{r eval=FALSE, include=FALSE}
set.seed(2021)
custom = train(cluster~.,
               data = covid_weekly_5[, 4:ncol(covid_weekly_5)],
               method = customRF,
               tuneGrid=tunegrid,
               trControl=control)

plot(custom)
```


```{r message=FALSE, warning=FALSE}
set.seed(2021)
library(caTools)

test_df = covid_weekly_1[sample.split(covid_weekly_1$cluster, SplitRatio = 0.2), ]
train_df = covid_weekly_1[-sample.split(covid_weekly_1$cluster, SplitRatio = 0.2), ]

rf_1 = randomForest(cluster ~ ., data = train_df[, 4:ncol(train_df)], ntree = 120, mtry = 3, importance = TRUE)

predictions = predict(rf_1, test_df[, 4:ncol(test_df)])
precision_val = posPredValue(predictions, test_df$cluster, positive = "1")
recall_val = sensitivity(predictions, test_df$cluster, positive = "1")
f1_1 = (2 * precision_val * recall_val) / (precision_val + recall_val)
AUC_1 = auc(test_df$cluster, as.numeric(predictions))

rf_metrics_1 = data.frame(Error_rate = min(rf_1$err.rate[, 1]), 
                          Accuracy = 1-min(rf_1$err.rate[, 1]),
                          F1 = f1_1,
                          AUC_ROC = AUC_1,
                          Set_NO = 1)
set.seed(2021)

test_df = covid_weekly_2[sample.split(covid_weekly_2$cluster, SplitRatio = 0.2), ]
train_df = covid_weekly_2[-sample.split(covid_weekly_2$cluster, SplitRatio = 0.2), ]

rf_2 = randomForest(cluster ~ ., data = train_df[, 4:ncol(train_df)], ntree = 100, mtry = 10, importance = TRUE)

predictions = predict(rf_2, test_df[, 4:ncol(test_df)])
precision_val = posPredValue(predictions, test_df$cluster, positive = "1")
recall_val = sensitivity(predictions, test_df$cluster, positive = "1")
f1_2 = (2 * precision_val * recall_val) / (precision_val + recall_val)
AUC_2 = auc(test_df$cluster, as.numeric(predictions))

rf_metrics_2 = data.frame(Error_rate = min(rf_2$err.rate[, 1]), 
                          Accuracy = 1-min(rf_2$err.rate[, 1]),
                          F1 = f1_2,
                          AUC_ROC = AUC_2,
                          Set_NO = 2)
set.seed(2021)
test_df = covid_weekly_3[sample.split(covid_weekly_3$cluster, SplitRatio = 0.2), ]
train_df = covid_weekly_3[-sample.split(covid_weekly_3$cluster, SplitRatio = 0.2), ]

rf_3 = randomForest(cluster ~ ., data = train_df[, 4:ncol(train_df)], ntree = 120, mtry = 6, importance = TRUE)

predictions = predict(rf_3, test_df[, 4:ncol(test_df)])
precision_val = posPredValue(predictions, test_df$cluster, positive = "1")
recall_val = sensitivity(predictions, test_df$cluster, positive = "1")
f1_3 = (2 * precision_val * recall_val) / (precision_val + recall_val)
AUC_3 = auc(test_df$cluster, as.numeric(predictions))

rf_metrics_3 = data.frame(Error_rate = min(rf_3$err.rate[, 1]), 
                          Accuracy = 1-min(rf_3$err.rate[, 1]),
                          F1 = f1_3,
                          AUC_ROC = AUC_3,
                          Set_NO = 3)
set.seed(2021)
test_df = covid_weekly_4[sample.split(covid_weekly_4$cluster, SplitRatio = 0.2), ]
train_df = covid_weekly_4[-sample.split(covid_weekly_4$cluster, SplitRatio = 0.2), ]

rf_4 = randomForest(cluster ~ ., data = train_df[, 4:ncol(train_df)], ntree = 120, mtry = 6, importance = TRUE)

predictions = predict(rf_4, test_df[, 4:ncol(test_df)])
precision_val = posPredValue(predictions, test_df$cluster, positive = "1")
recall_val = sensitivity(predictions, test_df$cluster, positive = "1")
f1_4 = (2 * precision_val * recall_val) / (precision_val + recall_val)
AUC_4 = auc(test_df$cluster, as.numeric(predictions))

rf_metrics_4 = data.frame(Error_rate = min(rf_4$err.rate[, 1]), 
                          Accuracy = 1-min(rf_4$err.rate[, 1]),
                          F1 = f1_4,
                          AUC_ROC = AUC_4,
                          Set_NO = 4)
set.seed(2021)

test_df = covid_weekly_5[sample.split(covid_weekly_5$cluster, SplitRatio = 0.2), ]
train_df = covid_weekly_5[-sample.split(covid_weekly_5$cluster, SplitRatio = 0.2), ]

rf_5 = randomForest(cluster ~ ., data = train_df[, 4:ncol(train_df)], ntree = 120, mtry = 6, importance = TRUE)

predictions = predict(rf_5, test_df[, 4:ncol(test_df)])
precision_val = posPredValue(predictions, test_df$cluster, positive = "1")
recall_val = sensitivity(predictions, test_df$cluster, positive = "1")
f1_5 = (2 * precision_val * recall_val) / (precision_val + recall_val)
AUC_5 = auc(test_df$cluster, as.numeric(predictions))

rf_metrics_5 = data.frame(Error_rate = min(rf_5$err.rate[, 1]), 
                          Accuracy = 1-min(rf_5$err.rate[, 1]),
                          F1 = f1_5,
                          AUC_ROC = AUC_5,
                          Set_NO = 5)

rf_metrics = rbind.data.frame(rf_metrics_1, rf_metrics_2, rf_metrics_3, rf_metrics_4, rf_metrics_5)

rf_metrics = rf_metrics[, c(5,2,1,3,4)]
rf_metrics[, 2:ncol(rf_metrics)] = round(rf_metrics[, 2:ncol(rf_metrics)], 4)
colnames(rf_metrics) = c("covid # data set", "OOB Accuracy Rate", "OOB Error Rate", "OOB F1", "OOB AUC-ROC")
```


```{r eval=FALSE, include=FALSE}
set.seed(2021)

tune_para_1 = tuneRF(covid_weekly_1[, 4:18], covid_weekly_1$cluster, ntreeTry = 100, improve = 0.05)
tune_para_1 = as.data.frame(tune_para_1)
mtry_num_1 = tune_para_1[which.min(tune_para_1$OOBError),1]

rf_1 = randomForest(cluster ~ ., data = covid_weekly_1[, 4:19], ntree = 100, mtry = mtry_num_1, importance = TRUE)

rf_metrics_1 = data.frame(Error_rate = min(rf_1$err.rate[, 1]), Accuracy = 1-min(rf_1$err.rate[, 1]), Set_NO = 1)

tune_para_2 = tuneRF(covid_weekly_2[, 4:18], covid_weekly_2$cluster, ntreeTry = 100, improve = 0.05)
tune_para_2 = as.data.frame(tune_para_2)
mtry_num_2 = tune_para_2[which.min(tune_para_2$OOBError),1]

rf_2 = randomForest(cluster ~ ., data = covid_weekly_2[, 4:19], ntree = 100, mtry = mtry_num_2, importance = TRUE)

rf_metrics_2 = data.frame(Error_rate = min(rf_2$err.rate[, 1]), Accuracy = 1-min(rf_2$err.rate[, 1]), Set_NO = 2)

tune_para_3 = tuneRF(covid_weekly_3[, 4:18], covid_weekly_3$cluster, ntreeTry = 100, improve = 0.05)
tune_para_3 = as.data.frame(tune_para_3)
mtry_num_3 = tune_para_3[which.min(tune_para_3$OOBError),1]

rf_3 = randomForest(cluster ~ ., data = covid_weekly_3[, 4:19], ntree = 100, mtry = mtry_num_3, importance = TRUE)

rf_metrics_3 = data.frame(Error_rate = min(rf_3$err.rate[, 1]), Accuracy = 1-min(rf_3$err.rate[, 1]), Set_NO = 3)

tune_para_4 = tuneRF(covid_weekly_4[, 4:18], covid_weekly_4$cluster, ntreeTry = 100, improve = 0.05)
tune_para_4 = as.data.frame(tune_para_4)
mtry_num_4 = tune_para_4[which.min(tune_para_4$OOBError),1]

rf_4 = randomForest(cluster ~ ., data = covid_weekly_4[, 4:19], ntree = 100, mtry = mtry_num_4, importance = TRUE)

rf_metrics_4 = data.frame(Error_rate = min(rf_4$err.rate[, 1]), Accuracy = 1-min(rf_4$err.rate[, 1]), Set_NO = 4)



tune_para_5 = tuneRF(covid_weekly_5[, 4:18], covid_weekly_5$cluster, ntreeTry = 100, improve = 0.05)
tune_para_5 = as.data.frame(tune_para_5)
mtry_num_5 = tune_para_5[which.min(tune_para_5$OOBError),1]

rf_5 = randomForest(cluster ~ ., data = covid_weekly_5[, 4:19], ntree = 100, mtry = mtry_num_5, importance = TRUE)

rf_metrics_5 = data.frame(Error_rate = min(rf_5$err.rate[, 1]), Accuracy = 1-min(rf_5$err.rate[, 1]), Set_NO = 5)


rf_metrics = rbind.data.frame(rf_metrics_1, rf_metrics_2, rf_metrics_3, rf_metrics_4, rf_metrics_5)

rf_metrics$Error_rate = round(rf_metrics$Error_rate, 4)
rf_metrics$Accuracy = round(rf_metrics$Accuracy, 4)
rf_metrics = rf_metrics[, c(3,2,1)]
colnames(rf_metrics) = c("covid # data set", "OOB Accuracy Rate", "OOB Error Rate")
```
 
```{r }
DT_metrics %>% group_by(Set_NO) %>% summarise(mean_acc = mean(Accuracy), mean_error = mean(Error_Rate))

DT = DT_metrics %>% 
  summarise(mean_acc = round(mean(Accuracy), 4), mean_error = round(mean(Error_Rate), 4)) %>% 
  mutate(Model = 'Decision Tree')

RF = rf_metrics %>% 
  summarise(mean_acc = round(mean(Accuracy),4), mean_error = round(mean(Error_rate), 4)) %>% 
  mutate(Model = 'Random Forest')

rf_metrics$Error_rate = round(rf_metrics$Error_rate, 4)
rf_metrics$Accuracy = round(rf_metrics$Error_rate, 4)


classification_models = rbind.data.frame(DT, RF)

classification_models
```

```{r}

AVE_DT_metrics[, 2:ncol(AVE_DT_metrics)] = round(AVE_DT_metrics[, 2:ncol(AVE_DT_metrics)] ,4)
classification_models_metrics = rf_metrics %>% left_join(AVE_DT_metrics, by = "covid # data set")
classification_models_metrics
ft = flextable(classification_models_metrics)

typology = data.frame(col_keys = colnames(classification_models_metrics),
                      what = c('covid # data set', 
                               'Random Forest', 'Random Forest', "Random Forest", "Random Forest",
                               'Decision Tree', 'Decision Tree', "Decision Tree", "Decision Tree"),
                      measures = c('covid # data set', 
                                   "Accuracy", "Error Rate", "F1", "AUC-ROC",
                                   "Accuracy", "Error Rate", "F1", "AUC-ROC" ))

ft = set_header_df(ft, mapping = typology, key = 'col_keys')
ft = merge_h(ft, part = 'header')
ft = merge_v(ft, j = 'covid # data set', part = 'header')
ft = theme_vanilla(ft)
ft = ft %>% align(align = "center", part = "all") %>% width(width = 3) %>% fontsize(size = 16, part = "all")

ft
colMeans(classification_models_metrics)
```


```{r}
model = glm(cluster ~ ., data = covid_weekly_1[, 4:ncol(covid_weekly_1)], family = 'binomial')
summary(model)
```

```{r}
plotcp(decision_tree)
```

